export const searchHeroBar = document.getElementById('searchHeroBar')
export const searchButton = document.getElementById('searchButton')
export const findRandomButton = document.getElementById('findRandomButton')
export const characterSearchResults = document.getElementById('characterSearchResults')

export const characterGalery = document.getElementById('characterGalery')
export const comicGalery = document.getElementById('comicGalery')
export const creatorsGalery = document.getElementById('creatorsGalery')
export const seriesGalery = document.getElementById('seriesGalery')
export const storiesGalery = document.getElementById('storiesGalery')
export const eventsGalery = document.getElementById('eventsGalery')

export const templateSearchResults = document.getElementById('templateSearchResults')
export const templateCharacterRender = document.getElementById('templateCharacterRender')
export const templateComicRender = document.getElementById('templateComicRender')
export const templateSeriesRender = document.getElementById('templateSeriesRender')
export const templateEventsRender = document.getElementById('templateEventsRender')
export const templateCreatorsRender = document.getElementById('templateCreatorsRender')
export const templateStoriesRender = document.getElementById('templateStoriesRender')